const recyclableItems = {
    papel: "azul",
    "papelão": "azul",
    "jornais": "azul",
    "jornal": "azul",
    "revistas": "azul",
    "revista": "azul",
    "folhas de caderno": "azul",
    "folha de caderno": "azul",
    "caixas de papelão": "azul",
    "caixa de papelão": "azul",
    "embalagens de papel": "azul",
    "embalagem de papel": "azul",
    "plástico": "vermelho",
    "plastico": "vermelho",
    "garrafas PET": "vermelho",
    "garrafa PET": "vermelho",
    "PET": "vermelho",
    "embalagens de plástico": "vermelho",
    "embalagem de plástico": "vermelho",
    "sacolas plásticas": "vermelho",
    "sacola plástica": "vermelho",
    "copos plásticos": "vermelho",
    "copo plástico": "vermelho",
    "potes de iogurte": "vermelho",
    "pote de iogurte": "vermelho",
    "tampas de plástico": "vermelho",
    "tampa de plástico": "vermelho",
    "tampinha": "vermelho",
    "tampinhas": "vermelho",
    "tampinha de plastico": "vermelho",
    "tampinha de plástico": "vermelho",
    "tampinhas de plastico": "vermelho",
    "tampinhas de plástico": "vermelho",
    "vidro": "verde",
    "garrafas de vidro": "verde",
    "garrafa de vidro": "verde",
    "potes de vidro": "verde",
    "pote de vidro": "verde",
    "frascos de vidro": "verde",
    "frasco de vidro": "verde",
    "cacos de vidro": "verde",
    "caco de vidro": "verde",
    "metal": "amarelo",
    "metais": "amarelo",
    "latas de alumínio": "amarelo",
     "latinha": "amarelo",
     "latinhas": "amarelo",
     "lata": "amarelo",
     "latas": "amarelo",
    "latas de aço": "amarelo",
    "tampas metálicas": "amarelo",
    "embalagens de alumínio": "amarelo",
    "ferragens": "amarelo",
    "madeira": "preto",
    "serragem": "preto",
    "tábuas": "preto",
    "tábua": "preto",
    "tabua": "preto",
    "tabuas": "preto",
    "móveis de madeira": "preto",
    "resíduos perigosos": "laranja",
    "pilhas": "laranja",
    "baterias": "laranja",
    "produtos químicos": "laranja",
    "lâmpadas fluorescentes": "laranja",
    "tintas": "laranja",
    "tinta": "laranja",
    "resíduos de hospitais e serviços de saúde": "branco",
    "resíduos": "branco",
    "resíduo": "branco",
    "residuos": "branco",
    "residuo": "branco",
    "algodões usados": "branco",
    "ataduras": "branco",
    "materiais cirúrgicos": "branco",
    "agulhas": "branco",
    "agulha": "branco",
    "lixo radioativo": "roxo",
    "materiais de laboratórios de radiologia": "roxo",
    "equipamentos de radioterapia": "roxo"
};
// Lista de tipos de lixo orgânicos
const organicItems = [
    "restos de comida",
    "resto de comida",
    "casca de fruta",
    "cascas de frutas",
    "casca de legume",
    "cascas de legumes",
    "borra de café",
    "borra de cafe",
    "borra café",
    "café",
    "folhas",
    "folha",
    "galhos",
    "galho",
    "grama",
    "ovos",
    "ovo",
    "pão",
    "casca de ovo",
    "sementes",
    "semente",
    "flores",
    "flor",
    "ervas daninhas", "casca de banana", "pele de banana",
        "cascas de maçã", "casca de maçã", "pele de maçã",
        "cascas de laranja", "casca de laranja", "pele de laranja",
        "cascas de limão", "casca de limão", "pele de limão",
        "cascas de abacate", "casca de abacate", "pele de abacate",
        "cascas de batata", "casca de batata", "pele de batata",
        "cascas de cenoura", "casca de cenoura", "pele de cenoura",
        "cascas de beterraba", "casca de beterraba", "pele de beterraba",
        "cascas de manga", "casca de manga", "pele de manga",
        "cascas de mamão", "casca de mamão", "pele de mamão",
        "cascas de melão", "casca de melão", "pele de melão",
        "cascas de melancia", "casca de melancia", "pele de melancia",
        "cascas de pepino", "casca de pepino", "pele de pepino",
        "cascas de abobrinha", "casca de abobrinha", "pele de abobrinha",
        "cascas de abacaxi", "casca de abacaxi", "pele de abacaxi",
        "cascas de pêssego", "casca de pêssego", "pele de pêssego",
        "cascas de nectarina", "casca de nectarina", "pele de nectarina",
        "cascas de pera", "casca de pera", "pele de pera",
        "cascas de kiwi", "casca de kiwi", "pele de kiwi",
        "cascas de maracujá", "casca de maracujá", "pele de maracujá",
        "cascas de coco", "casca de coco", "pele de coco",
        "cascas de tomate", "casca de tomate", "pele de tomate",
        "cascas de berinjela", "casca de berinjela", "pele de berinjela",
        "cascas de batata-doce", "casca de batata-doce", "pele de batata-doce",
        "cascas de chuchu", "casca de chuchu", "pele de chuchu",
        "cascas de inhame", "casca de inhame", "pele de inhame",
        "cascas de carambola", "casca de carambola", "pele de carambola",
        "cascas de goiaba", "casca de goiaba", "pele de goiaba",
        "cascas de tangerina", "casca de tangerina", "pele de tangerina",
        "cascas de caju", "casca de caju", "pele de caju",
        "cascas de jabuticaba", "casca de jabuticaba", "pele de jabuticaba",
        "cascas de lichia", "casca de lichia", "pele de lichia",
        "cascas de graviola", "casca de graviola", "pele de graviola",
        "cascas de morango", "casca de morango", 
        "cascas de ameixa", "casca de ameixa", "pele de ameixa",
        "cascas de figo", "casca de figo", "pele de figo",
        "cascas de uva", "casca de uva", "pele de uva",
        "cascas de abóbora", "casca de abóbora", "pele de abóbora",
        "cascas de mandioca", "casca de mandioca", "pele de mandioca",
        "cascas de maracujá", "casca de maracujá", "pele de maracujá",
        "cascas de cana-de-açúcar", "casca de cana-de-açúcar", "pele de cana-de-açúcar",
        "cascas de palmito", "casca de palmito", "pele de palmito",
        "cascas de alho", "casca de alho", "pele de alho",
        "cascas de cebola", "casca de cebola", "pele de cebola",
        "cascas de alho-poró", "casca de alho-poró", "pele de alho-poró",
        "cascas de nabo", "casca de nabo", "pele de nabo",
        "cascas de rabanete", "casca de rabanete", "pele de rabanete",
        "cascas de aipo", "casca de aipo", "pele de aipo",
        "cascas de couve-flor", "casca de couve-flor", "pele de couve-flor",
        "cascas de brócolis", "casca de brócolis", "pele de brócolis",
        "cascas de espinafre", "casca de espinafre", "pele de espinafre",
        "cascas de alface", "casca de alface", "pele de alface",
        "cascas de rúcula", "casca de rúcula", "pele de rúcula",
        "cascas de couve", "casca de couve", "pele de couve",
        "cascas de repolho", "casca de repolho", "pele de repolho",
        "cascas de agrião", "casca de agrião", "pele de agrião",
        "cascas de chicória", "casca de chicória", "pele de chicória",
        "cascas de erva-doce", "casca de erva-doce", "pele de erva-doce",
        "cascas de cebolinha", "casca de cebolinha", "pele de cebolinha",
        "cascas de coentro", "casca de coentro", "pele de coentro",
        "cascas de salsa", "casca de salsa", "pele de salsa",
        "cascas de manjericão", "casca de manjericão", "pele de manjericão",
        "cascas de hortelã", "casca de hortelã", "pele de hortelã",
        "cascas de alecrim", "casca de alecrim", "pele de alecrim",
        "cascas de tomilho", "casca de tomilho", "pele de tomilho",
        "cascas de sálvia", "casca de sálvia", "pele de sálvia",
        "cascas de louro", "casca de louro", "pele de louro",
        "cascas de estragão", "casca de estragão", "pele de estragão",
        "cascas de orégano", "casca de orégano", "pele de orégano",
        "cascas de pimentão", "casca de pimentão", "pele de pimentão",
        "cascas de pimenta", "casca de pimenta", "pele de pimenta",
        "cascas de gengibre", "casca de gengibre", "pele de gengibre",
        "cascas de cúrcuma", "casca de cúrcuma", "pele de cúrcuma",
        "cascas de cardamomo", "casca de cardamomo", "pele de cardamomo",
        "cascas de noz-moscada", "casca de noz-moscada", "pele de noz-moscada",
        "cascas de cravo-da-índia", "casca de cravo-da-índia", "pele de cravo-da-índia",
        "cascas de canela", "casca de canela", "pele de canela",
        "cascas de baunilha", "casca de baunilha", "pele de baunilha",
        "cascas de abobrinha italiana", "casca de abobrinha italiana", "pele de abobrinha italiana",
        "cascas de cogumelos", "casca de cogumelos", "pele de cogumelos",
        "cascas de jiló", "casca de jiló", "pele de jiló",
        "cascas de quiabo", "casca de quiabo", "pele de quiabo",
        "cascas de maxixe", "casca de maxixe", "pele de maxixe",
        "cascas de araticum", "casca de araticum", "pele de araticum",
        "cascas de atemoia", "casca de atemoia", "pele de atemoia",
        "cascas de biribá", "casca de biribá", "pele de biribá",
        "cascas de cupuaçu", "casca de cupuaçu", "pele de cupuaçu",
        "cascas de murici", "casca de murici", "pele de murici",
        "cascas de cajá", "casca de cajá", "pele de cajá",
        "cascas de acerola", "casca de acerola", "pele de acerola",
        "cascas de tamarindo", "casca de tamarindo", "pele de tamarindo",
        "cascas de seriguela", "casca de seriguela", "pele de seriguela",
        "cascas de pitanga", "casca de pitanga", "pele de pitanga",
        "cascas de cagaita", "casca de cagaita", "pele de cagaita",
        "cascas de cambuci", "casca de cambuci", "pele de cambuci",
        "cascas de jenipapo", "casca de jenipapo", "pele de jenipapo",
        "cascas de guabiroba", "casca de guabiroba", "pele de guabiroba",
        "cascas de araçá", "casca de araçá", "pele de araçá",
];

// Lista de cores das lixeiras
const binColors = {
    azul: "Recicláveis (Papel/Papelão)",
    vermelho: "Recicláveis (Plástico)",
    verde: "Recicláveis (Vidro)",
    amarelo: "Recicláveis (Metal)",
    preto: "Recicláveis (Madeira)",
    laranja: "Resíduos Perigosos",
    branco: "Resíduos de Hospitais e Serviços de Saúde",
    roxo: "Lixo Radioativo",
    marrom: "Orgânicos",
    cinza: "Não Recicláveis ou Contaminados"
};

document.getElementById('search-form').addEventListener('submit', function(event) {
    event.preventDefault(); // Impede o envio padrão do formulário
    var input = document.querySelector('.input-box').value.toLowerCase(); // Obtém o valor da entrada e converte para minúsculas
    var results = document.getElementById('results'); // Obtém a seção de resultados

    // Limpa resultados anteriores
    results.innerHTML = '';

    var resultItem = document.createElement('div');
    
    // Verifica se o item digitado é reciclável ou orgânico
    if (recyclableItems[input]) {
        const binColor = recyclableItems[input];
        resultItem.innerHTML = `
            <p>${input.charAt(0).toUpperCase() + input.slice(1)} é reciclável.</p>
            <p>Coloque na lixeira ${binColors[binColor]} (${binColor}).</p>
        `;
        resultItem.className = `result-item ${binColor}`;
    } else if (organicItems.includes(input)) {
        resultItem.innerHTML = `
            <p>${input.charAt(0).toUpperCase() + input.slice(1)} é orgânico.</p>
            <p>Coloque na lixeira ${binColors.marrom} (marrom).</p>
        `;
        resultItem.className = 'result-item marrom';
    } else {
        resultItem.innerHTML = `
            <p>${input.charAt(0).toUpperCase() + input.slice(1)} não é reciclável nem orgânico.</p>
            <p>Coloque na lixeira ${binColors.cinza} (cinza).</p>
        `;
        resultItem.className = 'result-item cinza';
    }

    results.appendChild(resultItem);

    // Limpa o campo de entrada
    document.querySelector('.input-box').value = '';
});