import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://cdn.awsli.com.br/600x1000/1982/1982052/produto/174027508/53c931b15d.jpg",
    title: "Alface",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "organicos",
    color: "white",
    category: "organicos",
    url: "./Checkout.js"
  },
  
  {
    img: "https://revistacampoenegocios.com.br/wp-content/uploads/2020/05/shutterstock_120016855.jpg",
    title: "Tomate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "organicos",
    color: "red",
    category: "organicos",
  },

  {
    img: "https://dcdn.mitiendanube.com/stores/004/172/605/products/vinho-tinto-merlot-seco-fino-bd1c7ab71dff01c43f17120646616622-1024-1024.png",
    title: "Vinho Tinto Seco",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "bebidas",
    color: "green",
    category: "bebidas",
  },
  {
    img: "https://www.proativaalimentos.com.br/image/cache/catalog/img_prod/oleo-essencia-morango-100ml-fruta-puro-essencia-massagem-D_NQ_NP_960102-MLB31202671230_062019-F[1]-1000x1000.jpg",
    title: "Morango",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://images.tcdn.com.br/img/img_prod/853101/panela_de_queijo_artesanal_alagoa_de_1_0_kg_serve_8_pessoas_23_1_10174749579395da4a68ec25893750dd.png",
    title: "Queijo Artesanal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "laticinios",
    color: "green",
    category: "laticinios",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTI62Vvoax9_pmq3uiacw06uUDh2M0OszzLA&s",
    title: "Beterraba",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "black",
    category: "organicos",
  },

  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSlSmMQmoGhFnckZYMqmw7jMfr6xdBRVHpsd-PrU0D1UFa3_NB0",
    title: "Repolho",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "white",
    category: "organicos",
  },

  {
    img: "https://acdn.mitiendanube.com/stores/001/093/547/products/coalhocancian1-b6447c3d5431ea9b1615924859909330-640-0.jpg",
    title: "Linguiça",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "defumados",
    color: "green",
    category: "defumados",
  },

  {
    img: "https://images.tcdn.com.br/img/img_prod/1255310/bacon_em_pedaco_artesanal_f_a_defumados_250g_13_1_76350e8261ccce125eb3e38b2962b992.png",
    title: "Bacon",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "defumados",
    color: "blue",
    category: "defumados",
  },

  {
    img: "https://cdn.awsli.com.br/300x300/2592/2592213/produto/236542477/costela-suina-defumada-7cmc1v4268.jpg",
    title: "Costelinha defumada",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "defumados",
    color: "green",
    category: "defumados",
  },
  {
    img: "https://s1.static.brasilescola.uol.com.br/be/2020/12/raiz-de-mandioca.jpg",
    title: "Mandioca",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "organicos",
    color: "red",
    category: "organicos",
  },
  {
    img: "https://scfoods.fbitsstatic.net/img/p/rabanete-400g-70578/257073.jpg?w=800&h=800&v=no-change&qs=ignore",
    title: "Rabanete",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://crsupermercados.com.br/cdn/shop/files/pepino-japones.png?v=1709206950",
    title: "Pepino",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "organicos",
    color: "white",
    category: "organicos",
  },
  {
    img: "https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/cenourao/media/uploads/produtos/foto/b28051667594erepolho.png",
    title: "Repolho Roxo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "organicos",
    color: "black",
    category: "organicos",
  },

  {
    img: "https://cdn.awsli.com.br/600x450/2080/2080181/produto/141869813/f03dc3a3fd.jpg",
    title: "Lícor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "bebidas",
    color: "green",
    category: "bebidas",
  },
  {
    img: "https://cdn.dooca.store/2179/products/siglebbfxjkz39jvdmddeyvlzscd1r2mqhjy_450x600+fill_ffffff.jpg?v=1675789319&webp=0",
    title: "Vinho Tinto Suave",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "bebidas",
    color: "red",
    category: "bebidas",
  },
  {
    img: "https://images.tcdn.com.br/img/img_prod/1012480/leite_cru_da_fazenda_2l_235_1_5986269a9084efd5fc656e60e4545d88.jpg",
    title: "Leite",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "laticinios",
    color: "white",
    category: "laticinios",
  },
  {
    img: "https://images.tcdn.com.br/img/img_prod/1080087/cachaca_artesanal_aguardente_novo_engenho_750ml_2013207_1_c0fd7fbe18a6467186e4a5df17cd1dcc.jpg",
    title: "Cachaça",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "bebidas",
    color: "blue",
    category: "bebidas",
  },
  {
    img: "https://giassi.vtexassets.com/arquivos/ids/1168762/Laranja-Bergamota-Kg.png?v=638510645928870000",
    title: "Bergamota",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://img.irroba.com.br/fit-in/600x600/filters:fill(fff):quality(80)/queijinc/catalog/produtos-pasta/doces-compota/doce-de-leite-pastoso-rural-caseiro-650g-2.JPG",
    title: "Doce de leite",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "laticinios",
    color: "black",
    category: "laticinios",
  },
  {
    img: "https://global.cdn.magazord.com.br/vasoeflor/img/2022/07/produto/1075/muda-limao-tahiti-90cm.jpg?ims=fit-in/800x800/filters:fill(white)",
    title: "Limão",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjDIZaF8Ce5tauod6Oj0W83k9XVp-B4elPeQ&s",
    title: "Maçã",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "organico",
    color: "red",
    category: "organico",
  },
  {
    img: "https://conteudo.imguol.com.br/c/entretenimento/5b/2019/09/12/caldo-de-cana-de-acucar-1568309899896_v2_1x1.jpg",
    title: "Caldo de Cana",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "bebidas",
    color: "red",
    category: "bebidas",
  },

  {
    img: "https://53662.cdn.simplo7.net/static/53662/sku/derivados-de-porco-1kg-de-salame-artesanal-defumado-italiano-p-1710623280696.jpg",
    title: "Salaminho",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "defumados",
    color: "black",
    category: "defumados",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT00sMxDb00S8RF7ui4d3Jqw-XSzSYJAVrrBg&s",
    title: "Banha de porco",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9JvZjiVg05OYfF0j1PDhyPnwxwxp4c5xnkg&s",
    title: "Criba",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "defumados",
    color: "white",
    category: "defumados",
  },
  {
    img: "https://revistacampoenegocios.com.br/wp-content/uploads/2020/11/Melancia-01.jpg",
    title: "Melância",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
  {
    img: "https://supernossoio.vtexassets.com/arquivos/ids/163673/Laranja-Bahia-Kg.jpg?v=637776840789600000",
    title: "Laranja",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "organicos",
    color: "black",
    category: "organicos",
  },
];

export default data;
